repos:
  - repo: https://github.com/accurics/terrascanter
    rev: v1.11.0
    hooks:
          - id: terraform-pre-commit   
            name: terrascan
            description: Runs terrascan on supported IaC templates.
            language: script
            entry: scripts/pre-commit-hook.sh  
            args: ['-i terraform -c config.yaml']